# Generated by Django 3.0.4 on 2021-02-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210208_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Post'),
        ),
    ]
